apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - name: http
    port: ${NGINX_PORT}
    protocol: TCP
    targetPort: ${NGINX_PORT}
  selector:
    app: nginx
  type: ClusterIP
status:
  loadBalancer: {}
