apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8s-ctl
  name: k8s-ctl
spec:
  ports:
  - name: http
    port: ${NGINX_PORT}
    protocol: TCP
    targetPort: ${NGINX_PORT}
  selector:
    app: k8s-ctl
  type: ClusterIP
status:
  loadBalancer: {}
