apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-ctl
  name: k8s-ctl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-ctl
  template:
    metadata:
      labels:
        app: k8s-ctl
    spec:

      volumes:
      - name: kubectl
        emptyDir: {}
      - name: helm
        emptyDir: {}        
      - name: shared-data
        emptyDir: {}        

      containers:
      - image: pinpindock/k8s-ctl # https://hub.docker.com/r/pinpindock/k8s-ctl
        name: k8s-ctl
        ports:
        - containerPort: 1025
        volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
        - name: helm
          mountPath: /usr/local/bin
        - name: kubectl
          mountPath: /usr/local/bin/kubectl