apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-ctl
  name: k8s-ctl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-ctl
  template:
    metadata:
      labels:
        app: k8s-ctl
    spec:

      volumes:
      - name: kubectl
        emptyDir: {}
      - name: helm
        emptyDir: {}
      - name: workdir
        emptyDir: {}

      # These containers are run during pod initialization
      initContainers:
      - name: install
        image: busybox
        command: ['sh', '-c', 'touch /tmp/dummyfile']
        volumeMounts:
        - name: workdir
          mountPath: /tmp/

      containers:
      - name: k8s-ctl
        image: pinpindock/k8s-ctl # https://hub.docker.com/r/pinpindock/k8s-ctl
        command: ['sh', '-c', 'i=0; while true; do echo ": $(date)"; i=$((i+1)); sleep 3600; done']
        ports:
        - containerPort: 4242
        volumeMounts:
        - name: helm
          mountPath: /usr/local/bin
        - name: kubectl
          mountPath: /usr/local/bin/kubectl

      - name:  busybox
        image:  busybox
        #command: ['sh', '-c', 'if [ ! -e /tmp/dummyfile]; then exit;fi;']
        command: ['sh', '-c', 'i=0; while true; do echo ": $(date)"; i=$((i+1)); sleep 3600; done']
        ports:
        - containerPort: 8042
        volumeMounts:
        - name: workdir
          mountPath: /tmp/
