apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-ctl
  name: k8s-ctl
spec:
  ports:
  - name: http
    port: 4242
    protocol: TCP
    targetPort: 4242
  selector:
    app: k8s-ctl
  type: ClusterIP
status:
  loadBalancer: {}
