apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8s-ctl
  name: k8s-ctl
spec:
  ports:
  - name: http
    port: 1025
    protocol: TCP
    targetPort: 1025
  selector:
    app: k8s-ctl
  type: ClusterIP
status:
  loadBalancer: {}
